services:
  frontend:
    build: .
    container_name: front-escola
    restart: always
    networks:
      - proxy
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 128M
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"

networks:
  proxy:
    external: true
