version: '3.8'

services:
  frontend:
    build: .
    container_name: front-escola
    restart: always
    ports:
      # O Nginx interno roda na 80. Vamos expor na 8080 no servidor Oracle.
      - "8080:80"